#    Copyright (C) 2019-2024  Marcus Rickert
#
#    See https://github.com/marcus67/python_base_app
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

##################################################################################
# Please, beware that this file has been generated! Do not make any changes here #
# but only to python_base_app/templates/gitlab-ci.template.yml!                  #
##################################################################################

version: 2.0

jobs:

  {%- if var.setup.angular_app_dir %}
  build_angular_app:
    docker:
      - image: "{{ var.setup.docker_image_build_angular }}"
    steps:
      - checkout
      # Check out all sub modules
      # See https://circleci.com/docs/2.0/configuration-reference/#checkout
      - run: git submodule sync
      - run: git submodule update --init

    {%- if var.setup.ci_pip_dependencies|length > 0 %}
      - run: ${PIP3} install  {%- for package in var.setup.ci_pip_dependencies %} {{package}}{% endfor %}
    {%- endif %}
      - run: PYTHONPATH={{ var.setup.contrib_dir }}/python_base_app python3 {{ var.setup.ci_toolbox_script }} --execute-stage {{ var.setup.ci_stage_build_angular_app }} --use-dev-dir=.
      - persist_to_workspace:
          root: {{ var.setup.angular_deployment_source_directory }}
          paths:
            - "**"
  {%- endif -%}

  {%- if var.setup.build_debian_package %}
  {% for image_info in var.setup.docker_images_test %}
  build_{{ image_info[0] }}:
    docker:
      - image: "{{ image_info[1] }}"
    steps:
      - checkout
{% if var.setup.angular_app_dir %}
      - attach_workspace:
          at: "{{ var.setup.angular_deployment_source_directory }}"
{% endif %}
      # Check out all sub modules
      # See https://circleci.com/docs/2.0/configuration-reference/#checkout
      - run: git submodule sync
      - run: git submodule update --init

  {%- if var.setup.ci_pip_dependencies|length > 0 %}
      - run: ./bin/pip3.sh install  {%- for package in var.setup.ci_pip_dependencies %} {{package}}{% endfor %}
  {%- endif %}
  {%- if var.setup.angular_app_dir %}
      - run: PYTHONPATH={{ var.setup.contrib_dir }}/python_base_app python3 {{ var.setup.ci_toolbox_script }} --execute-stage {{ var.setup.ci_stage_deploy_angular_app }} --use-dev-dir .
  {%- endif %}
      - run: PYTHONPATH={{ var.setup.contrib_dir }}/python_base_app python3 {{ var.setup.ci_toolbox_script }} --execute-stage {{ var.setup.ci_stage_build_package }} --use-dev-dir=.
      - run: PYTHONPATH={{ var.setup.contrib_dir }}/python_base_app python3 {{ var.setup.ci_toolbox_script }} --execute-stage {{ var.setup.ci_stage_install }}
  {%- if var.setup.run_test_suite %}
      - run: DELTA_PORT={{ loop.index0 }} PYTHONPATH={{ var.setup.contrib_dir }}/python_base_app python3 {{ var.setup.ci_toolbox_script }} --execute-stage {{ var.setup.ci_stage_test }} --use-dev-dir .
  {%- endif %}
      - run: codecov
      {% if loop.revindex == 1 %}
      - store_artifacts:
          path: htmlcov
      - store_artifacts:
          path: {{ var.setup.debian_build_dir }}/{{ var.setup.debian_package_name }}_{{ var.setup.version }}_{{ var.setup.debian_package_revision }}.deb
      - persist_to_workspace:
          root: "."
          paths:
            - {{ var.setup.debian_build_dir }}/{{ var.setup.debian_package_name }}_{{ var.setup.version }}_{{ var.setup.debian_package_revision }}.deb
      {% endif %}
  {% endfor %}
  {%- endif %}

  {%- if var.setup.build_pypi_package %}
  {% for image_info in var.setup.docker_images_test %}
  build_pypi_{{ image_info[0] }}:
    #working_directory: ~
    docker:
      - image: "{{ image_info[1] }}"
    steps:
      - checkout
  {% if var.setup.angular_app_dir %}
      - attach_workspace:
          at: "{{ var.setup.angular_deployment_source_directory }}"
  {% endif %}
      # Check out all sub modules
      # See https://circleci.com/docs/2.0/configuration-reference/#checkout
      - run: git submodule sync
      - run: git submodule update --init

  {%- if var.setup.ci_pip_dependencies|length > 0 %}
      - run: ./bin/pip3.sh install  {%- for package in var.setup.ci_pip_dependencies %} {{package}}{% endfor %}
  {%- endif %}
  {%- if var.setup.angular_app_dir %}
      - run: PYTHONPATH={{ var.setup.contrib_dir }}/python_base_app python3 {{ var.setup.ci_toolbox_script }} --execute-stage {{ var.setup.ci_stage_deploy_angular_app }} --use-dev-dir .
  {%- endif %}
      - run: PYTHONPATH={{ var.setup.contrib_dir }}/python_base_app python3 {{ var.setup.ci_toolbox_script }} --execute-stage {{ var.setup.ci_stage_build_package }} --use-dev-dir=.
      - store_artifacts:
          path: "dist/{{ var.setup.name }}-{{ var.setup.version }}.tar.gz"
      # Rename the artifact to a specific name, so that the artifacts uploaded by parallel jobs do not collide
      # with each other in common downstream jobs.
  {%- for package in python_packages %}
      - run: mv {{ package[0] }}/dist/{{ package[10] }}-{{ package[11] }}.tar.gz {{ package[0] }}/dist/{{ package[10] }}-{{ package[11] }}.tar.gz_{{ image_info[0] }}
      - persist_to_workspace:
          root: "."
          paths:
            - {{ package[0] }}/dist/{{ package[10] }}-{{ package[11] }}.tar.gz_{{ image_info[0] }}
  {%- endfor %}
  {% endfor %}
  {%- endif %}

  {%- if var.setup.build_pypi_package %}
  {% for image_info in var.setup.docker_images_test %}
  install_pypi_{{ image_info[0] }}:
    #working_directory: ~
    docker:
      - image: "{{ image_info[1] }}"
    steps:
      - checkout

      # Check out all sub modules
      # See https://circleci.com/docs/2.0/configuration-reference/#checkout
      - run: git submodule sync
      - run: git submodule update --init

      - attach_workspace:
          at: "."
  {%- for package in python_packages %}
      - run: mv {{ package[0] }}/dist/{{ package[10] }}-{{ package[11] }}.tar.gz_{{ image_info[0] }} {{ package[0] }}/dist/{{ package[10] }}-{{ package[11] }}.tar.gz
  {%- endfor %}

  {%- if var.setup.ci_pip_dependencies|length > 0 %}
      - run: ./bin/pip3.sh install  {%- for package in var.setup.ci_pip_dependencies %} {{package}}{% endfor %}
  {%- endif %}
      - run: PYTHONPATH={{ var.setup.contrib_dir }}/python_base_app python3 {{ var.setup.ci_toolbox_script }} --execute-stage {{ var.setup.ci_stage_install_pypi_package }} --use-dev-dir=.
  {%- if var.setup.run_test_suite %}
      - run: DELTA_PORT={{ (var.setup.docker_images_test | length) + loop.index0 }} PYTHONPATH={{ var.setup.contrib_dir }}/python_base_app python3 {{ var.setup.ci_toolbox_script }} --execute-stage {{ var.setup.ci_stage_test }}
  {%- endif %}
      - run: codecov
      {% if loop.revindex == 1 %}
      - store_artifacts:
          path: htmlcov
      {% endif %}
  {% endfor %}
  {%- endif %}

  {%- if var.setup.publish_pypi_package|length > 0 %}
  publish_pypi:
    #working_directory: ~
    docker:
      - image: {{ var.setup.docker_image_publish_pypi }}
    steps:
      - checkout

      # Check out all sub modules
      # See https://circleci.com/docs/2.0/configuration-reference/#checkout
      - run: git submodule sync
      - run: git submodule update --init
      - attach_workspace:
          at: "."
      # Choose the artifact of the last Python image (having the most up-to-date Python version)...
      - run: mv dist/{{ var.setup.name }}-{{ var.setup.version }}.tar.gz_{{ var.setup.docker_images_test[-1][0] }} dist/{{ var.setup.name }}-{{ var.setup.version }}.tar.gz

  {%- if var.setup.ci_pip_dependencies|length > 0 %}
      - run: ./bin/pip3.sh install  {%- for package in var.setup.ci_pip_dependencies %} {{package}}{% endfor %}
  {%- endif %}
      - run: PYTHONPATH={{ var.setup.contrib_dir }}/python_base_app python3 {{ var.setup.ci_toolbox_script }} --execute-stage {{ var.setup.ci_stage_publish_pypi_package }} --use-dev-dir=.
  {%- endif %}

  {%- if var.setup.build_debian_package %}
  deploy:
    docker:
      - image: {{ var.setup.docker_image_publish_debian }}
    steps:
      - checkout
      - attach_workspace:
          at: "."
      - run: git submodule sync
      - run: git submodule update --init
      - run: PYTHONPATH={{ var.setup.contrib_dir }}/python_base_app python3 {{ var.setup.ci_toolbox_script }} --execute-stage {{ var.setup.ci_stage_publish_package }}
  {%- endif %}

  {%- if var.setup.build_debian_package and var.setup.docker_contexts|length > 0 %}
  docker:
    docker:
      - image: {{ var.setup.docker_image_docker }}
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - attach_workspace:
          at: "."
      - setup_remote_docker:
          docker_layer_caching: false
  {%- if var.setup.ci_pip_dependencies|length > 0 %}
      - run: ./bin/pip3.sh install  {%- for package in var.setup.ci_pip_dependencies %} {{package}}{% endfor %}
  {%- endif %}
      - run: PYTHONPATH={{ var.setup.contrib_dir }}/python_base_app python3 {{ var.setup.ci_toolbox_script }} --execute-stage {{ var.setup.ci_stage_build_docker_images }}
  {%- endif %}

workflows:
    version: 2
    build_and_deploy:
      jobs:
  {% if var.setup.angular_app_dir %}
        - build_angular_app
  {% endif -%}
  {%- if var.setup.build_debian_package %}
  {% if var.setup.angular_app_dir %}
  {% for image_info in var.setup.docker_images_test %}
        - build_{{ image_info[0] }}:
            requires:
              - build_angular_app
  {% endfor %}
  {% else %}
  {% for image_info in var.setup.docker_images_test %}
        - build_{{ image_info[0] }}
  {% endfor %}
  {% endif -%}
{%- if var.setup.publish_debian_package|length > 0 %}
        - deploy:
            requires:
  {% for image_info in var.setup.docker_images_test %}
              - build_{{ image_info[0] }}
  {% endfor %}
            filters:
              branches:
                only:
  {%- for branch in var.setup.publish_debian_package %}
                  - {{ branch }}
  {%- endfor %}
  {%- if var.setup.build_debian_package and var.setup.docker_contexts|length > 0 %}
        - docker:
  {%- endif %}
            requires:
  {%- if var.setup.publish_pypi_package|length > 0 %}
              - publish_pypi
  {%- endif %}
  {% for image_info in var.setup.docker_images_test %}
              - build_{{ image_info[0] }}
  {% endfor %}
  {%- endif %}
  {%- endif %}

  {%- if var.setup.build_pypi_package %}
  {% if var.setup.angular_app_dir %}
  {% for image_info in var.setup.docker_images_test %}
        - build_pypi_{{ image_info[0] }}:
            requires:
              - build_angular_app
  {% endfor %}
  {% else %}
  {% for image_info in var.setup.docker_images_test %}
        - build_pypi_{{ image_info[0] }}
  {% endfor %}
  {% endif %}
  {% for image_info in var.setup.docker_images_test %}
        - install_pypi_{{ image_info[0] }}:
            requires:
              - build_pypi_{{ image_info[0] }}
  {% endfor %}
  {%- if var.setup.publish_pypi_package|length > 0 %}
        - publish_pypi:
            requires:
  {%- for image_info in var.setup.docker_images_test %}
              - install_pypi_{{ image_info[0] }}
  {%- endfor %}
            filters:
              branches:
                only:
  {%- for branch in var.setup.publish_pypi_package %}
                  - {{ branch }}
  {%- endfor %}
  {%- endif %}
  {%- endif %}
